// <auto-generated />
using ControllerProgrammer.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControllerProgrammer.Data.Migrations
{
    [DbContext(typeof(ProgrammerContext))]
    partial class ProgrammerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ControllerProgrammer.Data.Model.Led", b =>
                {
                    b.Property<int>("LedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wavelength")
                        .HasColumnType("INTEGER");

                    b.HasKey("LedId");

                    b.ToTable("Leds", "controlDb");
                });

            modelBuilder.Entity("ControllerProgrammer.Data.Model.PowerDensity", b =>
                {
                    b.Property<int>("PowerDensityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Current")
                        .HasColumnType("REAL");

                    b.Property<int>("LedId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PowerDenisty")
                        .HasColumnType("REAL");

                    b.HasKey("PowerDensityId");

                    b.HasIndex("LedId");

                    b.ToTable("PowerDensities", "controlDb");
                });

            modelBuilder.Entity("ControllerProgrammer.Data.Model.PowerDensity", b =>
                {
                    b.HasOne("ControllerProgrammer.Data.Model.Led", "Led")
                        .WithMany("PowerDensities")
                        .HasForeignKey("LedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Led");
                });

            modelBuilder.Entity("ControllerProgrammer.Data.Model.Led", b =>
                {
                    b.Navigation("PowerDensities");
                });
#pragma warning restore 612, 618
        }
    }
}
